
/**
 * Lockstep Platform SDK for Java
 *
 * (c) 2021-2023 Lockstep, Inc.
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 *
 * @author     Lockstep Network <support@lockstep.io>
 * @copyright  2021-2023 Lockstep, Inc.
 * @link       https://github.com/Lockstep-Network/lockstep-sdk-java
 */


package io.lockstep.api.clients;

import io.lockstep.api.LockstepApi;
import io.lockstep.api.RestRequest;
import io.lockstep.api.LockstepResponse;
import org.jetbrains.annotations.NotNull;
import org.jetbrains.annotations.Nullable;
import io.lockstep.api.models.InvoiceModel;

import io.lockstep.api.models.DeleteResult;
import io.lockstep.api.models.InvoiceWorkflowStatusHistoryModel;
import io.lockstep.api.BlobRequest;
import io.lockstep.api.models.BulkDeleteRequestModel;
import io.lockstep.api.FetchResult;
import com.google.gson.reflect.TypeToken;
import io.lockstep.api.models.InvoiceSummaryModelInvoiceSummaryTotalsModelSummaryFetchResult;
import io.lockstep.api.models.AtRiskInvoiceSummaryModel;

/**
 * Contains all methods related to Invoices
 */
public class InvoicesClient
{
    private LockstepApi client;

    /**
     * Constructor for the Invoices API collection
     *
     * @param client A {@link io.lockstep.api.LockstepApi} platform client
     */
    public InvoicesClient(@NotNull LockstepApi client) {
        super();
        this.client = client;
    }

    /**
     * Retrieves the Invoice specified by this unique identifier, optionally including nested data sets.
     *
     * An Invoice represents a bill sent from one company to another.  The creator of the invoice is identified by the `CompanyId` field, and the recipient of the invoice is identified by the `CustomerId` field.  Most invoices are uniquely identified both by a Lockstep Platform ID number and a customer ERP "key" that was generated by the system that originated the invoice.  Invoices have a total amount and a due date, and when some payments have been made on the Invoice the `TotalAmount` and the `OutstandingBalanceAmount` may be different.
     *
     * @param id The unique Lockstep Platform ID number of this invoice; NOT the customer's ERP key
     * @param include To fetch additional data on this object, specify the list of elements to retrieve. Available collections: Addresses, Lines, Payments, Notes, Attachments, Company, Customer, CustomFields, CreditMemos, WorkflowStatuses
     * @return A {@link io.lockstep.api.LockstepResponse} containing the results
     */
    public @NotNull LockstepResponse<InvoiceModel> retrieveInvoice(@NotNull String id, @Nullable String include)
    {
        RestRequest<InvoiceModel> r = new RestRequest<InvoiceModel>(this.client, "GET", "/api/v1/Invoices/{id}");
        r.AddPath("{id}", id.toString());
        r.AddQuery("include", include.toString());
        return r.Call(InvoiceModel.class);
    }

    /**
     * Updates an existing Invoice with the information supplied to this PATCH call.
     *
     * The PATCH method allows you to change specific values on the object while leaving other values alone.  As input you should supply a list of field names and new values.  If you do not provide the name of a field, that field will remain unchanged.  This allows you to ensure that you are only updating the specific fields desired.
     *
     * An Invoice represents a bill sent from one company to another.  The creator of the invoice is identified by the `CompanyId` field, and the recipient of the invoice is identified by the `CustomerId` field.  Most invoices are uniquely identified both by a Lockstep Platform ID number and a customer ERP "key" that was generated by the system that originated the invoice.  Invoices have a total amount and a due date, and when some payments have been made on the Invoice the `TotalAmount` and the `OutstandingBalanceAmount` may be different.
     *
     * @param id The unique Lockstep Platform ID number of the invoice to update; NOT the customer's ERP key
     * @param body A list of changes to apply to this Invoice
     * @return A {@link io.lockstep.api.LockstepResponse} containing the results
     */
    public @NotNull LockstepResponse<InvoiceModel> updateInvoice(@NotNull String id, @NotNull Object body)
    {
        RestRequest<InvoiceModel> r = new RestRequest<InvoiceModel>(this.client, "PATCH", "/api/v1/Invoices/{id}");
        r.AddPath("{id}", id.toString());
        r.AddBody(body);
        return r.Call(InvoiceModel.class);
    }

    /**
     * Deletes the Invoice referred to by this unique identifier. An Invoice represents a bill sent from one company to another.  The creator of the invoice is identified by the `CompanyId` field, and the recipient of the invoice is identified by the `CustomerId` field.  Most invoices are uniquely identified both by a Lockstep Platform ID number and a customer ERP "key" that was generated by the system that originated the invoice.  Invoices have a total amount and a due date, and when some payments have been made on the Invoice the `TotalAmount` and the `OutstandingBalanceAmount` may be different.
     *
     * @param id The unique Lockstep Platform ID number of the invoice to delete; NOT the customer's ERP key
     * @return A {@link io.lockstep.api.LockstepResponse} containing the results
     */
    public @NotNull LockstepResponse<DeleteResult> deleteInvoice(@NotNull String id)
    {
        RestRequest<DeleteResult> r = new RestRequest<DeleteResult>(this.client, "DELETE", "/api/v1/Invoices/{id}");
        r.AddPath("{id}", id.toString());
        return r.Call(DeleteResult.class);
    }

    /**
     * Retrieves the Invoice Workflow Status Histories specified by the unique identifier of the Invoice.
     *
     * An Invoice Workflow Status History represents a prior Workflow Status that was assigned to an Invoice.
     *
     * @param id The unique Accounting Data Service Platform ID number of the Invoice.
     * @return A {@link io.lockstep.api.LockstepResponse} containing the results
     */
    public @NotNull LockstepResponse<InvoiceWorkflowStatusHistoryModel[]> retrieveInvoiceWorkflowStatusHistories(@NotNull String id)
    {
        RestRequest<InvoiceWorkflowStatusHistoryModel[]> r = new RestRequest<InvoiceWorkflowStatusHistoryModel[]>(this.client, "GET", "/api/v1/Invoices/{id}/workflow-status-history");
        r.AddPath("{id}", id.toString());
        return r.Call(InvoiceWorkflowStatusHistoryModel[].class);
    }

    /**
     * Creates one or more Invoices within this account and returns the records as created.
     *
     * An Invoice represents a bill sent from one company to another.  The creator of the invoice is identified by the `CompanyId` field, and the recipient of the invoice is identified by the `CustomerId` field.  Most invoices are uniquely identified both by a Lockstep Platform ID number and a customer ERP "key" that was generated by the system that originated the invoice.  Invoices have a total amount and a due date, and when some payments have been made on the Invoice the `TotalAmount` and the `OutstandingBalanceAmount` may be different.
     *
     * @param customerCompanyId The ID of the customer company. Only to be used with the UBL file upload multipart/form-data option.
     * @param filename The full path of a file to upload to the API
     * @param body Upload a UBL file or provide an InvoiceModel array
     * @return A {@link io.lockstep.api.LockstepResponse} containing the results
     */
    public @NotNull LockstepResponse<InvoiceModel[]> createInvoices(@Nullable String customerCompanyId, @NotNull byte[] filename, @NotNull InvoiceModel[] body)
    {
        RestRequest<InvoiceModel[]> r = new RestRequest<InvoiceModel[]>(this.client, "POST", "/api/v1/Invoices");
        r.AddQuery("customerCompanyId", customerCompanyId.toString());
        r.AddBody(body);
        return r.Call(InvoiceModel[].class);
    }

    /**
     * Delete the Invoices referred to by these unique identifiers.
     *
     * An Invoice represents a bill sent from one company to another.  The creator of the invoice is identified by the `CompanyId` field, and the recipient of the invoice is identified by the `CustomerId` field.  Most invoices are uniquely identified both by a Lockstep Platform ID number and a customer ERP "key" that was generated by the system that originated the invoice.  Invoices have a total amount and a due date, and when some payments have been made on the Invoice the `TotalAmount` and the `OutstandingBalanceAmount` may be different.
     *
     * @param body The unique Lockstep Platform ID numbers of the Invoices to delete; NOT the customer's ERP keys
     * @return A {@link io.lockstep.api.LockstepResponse} containing the results
     */
    public @NotNull LockstepResponse<DeleteResult> deleteInvoices(@NotNull BulkDeleteRequestModel body)
    {
        RestRequest<DeleteResult> r = new RestRequest<DeleteResult>(this.client, "DELETE", "/api/v1/Invoices");
        r.AddBody(body);
        return r.Call(DeleteResult.class);
    }

    /**
     * Queries Invoices for this account using the specified filtering, sorting, nested fetch, and pagination rules requested.
     *
     * More information on querying can be found on the [Searchlight Query Language](https://developer.lockstep.io/docs/querying-with-searchlight) page on the Lockstep Developer website.
     *
     * An Invoice represents a bill sent from one company to another.  The creator of the invoice is identified by the `CompanyId` field, and the recipient of the invoice is identified by the `CustomerId` field.  Most invoices are uniquely identified both by a Lockstep Platform ID number and a customer ERP "key" that was generated by the system that originated the invoice.  Invoices have a total amount and a due date, and when some payments have been made on the Invoice the `TotalAmount` and the `OutstandingBalanceAmount` may be different.
     *
     * @param filter The filter for this query. See [Searchlight Query Language](https://developer.lockstep.io/docs/querying-with-searchlight)
     * @param include To fetch additional data on this object, specify the list of elements to retrieve. Available collections: Addresses, Lines, Payments, Notes, Attachments, Company, Customer, CustomFields, CreditMemos, WorkflowStatuses
     * @param order The sort order for this query. See See [Searchlight Query Language](https://developer.lockstep.io/docs/querying-with-searchlight)
     * @param pageSize The page size for results (default 250, maximum of 500). See [Searchlight Query Language](https://developer.lockstep.io/docs/querying-with-searchlight)
     * @param pageNumber The page number for results (default 0). See [Searchlight Query Language](https://developer.lockstep.io/docs/querying-with-searchlight)
     * @return A {@link io.lockstep.api.LockstepResponse} containing the results
     */
    public @NotNull LockstepResponse<FetchResult<InvoiceModel>> queryInvoices(@Nullable String filter, @Nullable String include, @Nullable String order, @Nullable Integer pageSize, @Nullable Integer pageNumber)
    {
        RestRequest<FetchResult<InvoiceModel>> r = new RestRequest<FetchResult<InvoiceModel>>(this.client, "GET", "/api/v1/Invoices/query");
        r.AddQuery("filter", filter.toString());
        r.AddQuery("include", include.toString());
        r.AddQuery("order", order.toString());
        r.AddQuery("pageSize", pageSize.toString());
        r.AddQuery("pageNumber", pageNumber.toString());
        return r.Call(new TypeToken<FetchResult<InvoiceModel>>() {}.getType());
    }

    /**
     * Retrieves a PDF file for this invoice if it is of one of the supported invoice types and has been synced using an app enrollment to one of the supported apps.
     *
     * Sage Intacct supports AR Invoices.
     *
     * QuickBooks Online supports AR Invoices, and AR Credit Memos.
     *
     * Xero supports AR Invoices, AP Invoices, AR Credit Memos, and AP Credit Memos.
     *
     * For other ERPs, the supported types will depend on the synced data.
     *
     * @param id The unique Lockstep Platform ID number of this invoice; NOT the customer's ERP key
     * @return A {@link io.lockstep.api.LockstepResponse} containing the results
     */
    public @NotNull LockstepResponse<byte[]> retrieveinvoicePDF(@NotNull String id)
    {
        BlobRequest r = new BlobRequest(this.client, "GET", "/api/v1/Invoices/{id}/pdf");
        r.AddPath("{id}", id.toString());
        return r.Call();
    }

    /**
     * Checks for whether a PDF file for this invoice exists if it is of one of the supported invoice types and has been synced using an app enrollment to one of the supported apps.
     *
     * Sage Intacct supports AR Invoices.
     *
     * QuickBooks Online supports AR Invoices, and AR Credit Memos.
     *
     * Xero supports AR Invoices, AP Invoices, AR Credit Memos, and AP Credit Memos.
     *
     * For other ERPs, the supported types will depend on the synced data.
     *
     * @param id The unique Lockstep Platform ID number of this invoice; NOT the customer's ERP key
     * @return A {@link io.lockstep.api.LockstepResponse} containing the results
     */
    public @NotNull LockstepResponse<byte[]> checkinvoicePDF(@NotNull String id)
    {
        BlobRequest r = new BlobRequest(this.client, "HEAD", "/api/v1/Invoices/{id}/pdf");
        r.AddPath("{id}", id.toString());
        return r.Call();
    }

    /**
     * Queries Invoices for this account using the specified filtering, sorting, nested fetch, and pagination rules requested.  Display the results using the Invoice Summary View format.
     *
     * More information on querying can be found on the [Searchlight Query Language](https://developer.lockstep.io/docs/querying-with-searchlight) page on the Lockstep Developer website.
     *
     * The Invoice Summary View represents a slightly different view of the data and includes some extra fields that might be useful.  For more information, see the data format of the Invoice Summary Model.
     *
     * @param filter The filter for this query. See [Searchlight Query Language](https://developer.lockstep.io/docs/querying-with-searchlight)
     * @param include To fetch additional data on this object, specify the list of elements to retrieve. Available collections: Summary, Aging
     * @param order The sort order for this query. See See [Searchlight Query Language](https://developer.lockstep.io/docs/querying-with-searchlight)
     * @param pageSize The page size for results (default 250, maximum of 500). See [Searchlight Query Language](https://developer.lockstep.io/docs/querying-with-searchlight)
     * @param pageNumber The page number for results (default 0). See [Searchlight Query Language](https://developer.lockstep.io/docs/querying-with-searchlight)
     * @return A {@link io.lockstep.api.LockstepResponse} containing the results
     */
    public @NotNull LockstepResponse<InvoiceSummaryModelInvoiceSummaryTotalsModelSummaryFetchResult> queryInvoiceSummaryView(@Nullable String filter, @Nullable String include, @Nullable String order, @Nullable Integer pageSize, @Nullable Integer pageNumber)
    {
        RestRequest<InvoiceSummaryModelInvoiceSummaryTotalsModelSummaryFetchResult> r = new RestRequest<InvoiceSummaryModelInvoiceSummaryTotalsModelSummaryFetchResult>(this.client, "GET", "/api/v1/Invoices/views/summary");
        r.AddQuery("filter", filter.toString());
        r.AddQuery("include", include.toString());
        r.AddQuery("order", order.toString());
        r.AddQuery("pageSize", pageSize.toString());
        r.AddQuery("pageNumber", pageNumber.toString());
        return r.Call(InvoiceSummaryModelInvoiceSummaryTotalsModelSummaryFetchResult.class);
    }

    /**
     * Queries At Risk Invoices for this account using the specified filtering, sorting, nested fetch, and pagination rules requested.  Display the results using the At Risk Invoice Summary View format.
     *
     * More information on querying can be found on the [Searchlight Query Language](https://developer.lockstep.io/docs/querying-with-searchlight) page on the Lockstep Developer website.
     *
     * The At Risk Invoice Summary View represents a slightly different view of the data and includes some extra fields that might be useful.  For more information, see the data format of the At Risk Invoice Summary Model.
     *
     * @param filter The filter for this query. See [Searchlight Query Language](https://developer.lockstep.io/docs/querying-with-searchlight)
     * @param include To fetch additional data on this object, specify the list of elements to retrieve. No collections are currently available but may be offered in the future
     * @param order The sort order for this query. See See [Searchlight Query Language](https://developer.lockstep.io/docs/querying-with-searchlight)
     * @param pageSize The page size for results (default 250, maximum of 500). See [Searchlight Query Language](https://developer.lockstep.io/docs/querying-with-searchlight)
     * @param pageNumber The page number for results (default 0). See [Searchlight Query Language](https://developer.lockstep.io/docs/querying-with-searchlight)
     * @return A {@link io.lockstep.api.LockstepResponse} containing the results
     */
    public @NotNull LockstepResponse<FetchResult<AtRiskInvoiceSummaryModel>> queryAtRiskView(@Nullable String filter, @Nullable String include, @Nullable String order, @Nullable Integer pageSize, @Nullable Integer pageNumber)
    {
        RestRequest<FetchResult<AtRiskInvoiceSummaryModel>> r = new RestRequest<FetchResult<AtRiskInvoiceSummaryModel>>(this.client, "GET", "/api/v1/Invoices/views/at-risk-summary");
        r.AddQuery("filter", filter.toString());
        r.AddQuery("include", include.toString());
        r.AddQuery("order", order.toString());
        r.AddQuery("pageSize", pageSize.toString());
        r.AddQuery("pageNumber", pageNumber.toString());
        return r.Call(new TypeToken<FetchResult<AtRiskInvoiceSummaryModel>>() {}.getType());
    }
}
