
/**
 * Lockstep Platform SDK for Java
 *
 * (c) 2021-2023 Lockstep, Inc.
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 *
 * @author     Lockstep Network <support@lockstep.io>
 * @copyright  2021-2023 Lockstep, Inc.
 * @link       https://github.com/Lockstep-Network/lockstep-sdk-java
 */


package io.lockstep.api.models;

import org.jetbrains.annotations.NotNull;
import org.jetbrains.annotations.Nullable;

/**
 * Represents the email reply suggestion from the SAGE GMS API
 */
public class EmailReplyGeneratorSuggestions
{
    private @Nullable String kind;
    private @Nullable String body;

    /**
     * The kind of reply generated by the GMS Api
     *
     * @return The field kind
     */
    public @Nullable String getKind() { return this.kind; }
    /**
     * The kind of reply generated by the GMS Api
     *
     * @param value The new value for kind
     */
    public void setKind(@Nullable String value) { this.kind = value; }
    /**
     * The body of the reply generated by the GMS Api
     *
     * @return The field body
     */
    public @Nullable String getBody() { return this.body; }
    /**
     * The body of the reply generated by the GMS Api
     *
     * @param value The new value for body
     */
    public void setBody(@Nullable String value) { this.body = value; }
};
